version: '3.9'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cr3t
      - MYSQL_PASSWORD=An0th3rs3cr3t
      - MYSQL_USER=dbuser
      - MYSQL_DATABASE=users_db
